# Generated by Django 3.1.5 on 2021-02-06 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcz', '0002_categorie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categorie',
        ),
    ]
