# Generated by Django 3.1.5 on 2021-02-12 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcz', '0005_subcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'Subcategories'},
        ),
    ]
